### DISCUSSION TITLE
docker xhofe/alist:v3.3.0 不能挂载阿里云盘

### DISCUSSION THREAD

**Discussion by Key789** [AlistGo/alist#2207] [General]
![image](https://user-images.githubusercontent.com/104561598/199921906-74fd0e60-8774-468a-b1b7-7b845619be19.png)
试了两个docker版本 v3.3.0 v3.1.0 均提示
"https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
v3.3.0 win11版本运行挂载正常

**Comment by Key789** [comment]
修改了宿主的dns地址，重启容器解决。

**Reply by Jue-Xu** [reply]
你好，我不大明白“修改了宿主的dns地址”的意思。我重启了alist docker和vps，但是没有解决问题。

**Reply by Key789** [reply]
我调试发现是我的上级路由拒绝了docker内的DNS解析，所以我把运行docker主机的DNS设成了114。

**Reply by Jue-Xu** [reply]
谢谢回复。我再多问一句，“把运行docker主机的DNS”是指 运行docker的系统（比如Linux）的DNS 是吗？ 

我在docker-compose.yml 修改了DNS
```
  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
        - '/root/vps/docker/alist:/alist/data'
    ports:
        - '5244:5244'
    dns:
        - 114.114.114.114
        - 9.9.9.9
    restart: always
```
但是没有效果，而且会把所有设置的网盘抹除了。
