### DISCUSSION TITLE
Alist是不是无法挂载只有ipv6地址的存储

### DISCUSSION THREAD

**Discussion by sola614** [AlistGo/alist#4792] [General]
家里路由器用的openwrt，装了Alist挂载了本地磁盘，也做了ddns，然后我想在vps通过Alist V3挂载，结果发现报错了
```
Failed init storage: Get "http://xxx.com:5244/api/me": dial tcp [**************************************]:5244: connect: cannot assign requested address
```
在vps命令行curl是有结果返回的，说明是有ipv6访问能力

**Comment by missorforget** [comment]
+1, 浏览器正常访问

**Comment by jkjoy** [comment]
我估计是Alist没有监听IPv6,因为我也遇到这样的情况

**Comment by uxfion** [comment]
我也遇到这个问题了，浏览器访问纯ipv6 alist没有问题，但是用其他支持ipv6的vps（且docker开启了ipv6）挂载纯ipv6 alist存储就会出现如下问题。
```
Get "https://example.com:5344/api/me": dial tcp [240x:xxxx:xxxx]:5344: connect: network is unreachable
```
翻了一下issue好像也没有相关的

**Comment by uxfion** [comment]
解决了，是docker设置的问题，参考<https://docs.docker.com/config/daemon/ipv6/>

## TL;DR
- `vim /etc/docker/daemon.json`
```
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```
- add ipv6 support for `docker-compose.yml`
```
    networks:
      - ip6net
 networks:
   ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:db8::/64
```
