### DISCUSSION TITLE
长文件名的文件，文件名在网页显示不全，希望能增加文件名多行的功能

### DISCUSSION THREAD

**Discussion by Nahuimi** [AlistGo/alist#4980] [Ideas]
文件名比较长的文件，在网页在列表视图下会文件名显示不全，特别是在手机端，希望能增加文件名能多行，把文件名全部显示的功能
![Screenshot_20230810-102003_Via.png](https://github.com/alist-org/alist/assets/46513301/059c2d9e-880d-44b3-b8c9-8df749094377)

**Comment by anwen-anyi** [comment]
~~可以在后台 设置-->全局中的`自定头部`或者`自定义内容`填写如下CSS~~     呃，手机端设置的话好像有问题......
```css
<style>
/* 文字超出进行换行 */
.name-box .name {
	white-space: unset !important;
	overflow: unset !important;
}
</style>
```
