### DISCUSSION TITLE
使用aria2离线下载失败，是否是我配置出现了问题？

### DISCUSSION THREAD

**Discussion by wlybq** [AlistGo/alist#5050] [Q&A]
软件版本：v3.25.1
![1031692474610_.pic.jpg](http://bookstackapp.tools.chenmingjie121.top:1280/uploads/images/gallery/2023-08/scaled-1680-/1031692474610-pic.jpg)

alist是部署在远程linux服务器上的，以下是alist的docker-compse文件：
```yaml
version: "3"

networks:
  alist:
    external: false

services:
  alist:
    image: xhofe/alist-aria2:latest
    container_name: alist
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: always
    networks:
      - alist
    volumes:
      - ./alist:/opt/alist/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5244:5244"
```
aria2是运行在我本地电脑的，现在问题来了——

我在使用本地aria2进行离线下载时，得到了aria2返回的以下错误
```
{"id":"0.3016542202171091","jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}
```
我查看控制台发现下载请求体中没有携带token，如下图：
![1021692474576_.pic.jpg](http://bookstackapp.tools.chenmingjie121.top:1280/uploads/images/gallery/2023-08/scaled-1680-/1021692474576-pic.jpg)

但是我查看了我的alist配置：
![1041692474626_.pic.jpg](http://bookstackapp.tools.chenmingjie121.top:1280/uploads/images/gallery/2023-08/scaled-1680-/1041692474626-pic.jpg)

和我本地的aria2配置：
![1051692474729_.pic.jpg](http://bookstackapp.tools.chenmingjie121.top:1280/uploads/images/gallery/2023-08/scaled-1680-/1051692474729-pic.jpg)

密码是对的，而且alist中我也找不到其他地方配置请求aria2的token了，所以是否还有我不知道的配置？或者是其他的原因？
