### DISCUSSION TITLE
当Alist和qbittorrent都使用dock安装时出现的权限问题。

### DISCUSSION THREAD

**Discussion by liangzilixueha** [AlistGo/alist#5791] [Q&A]
前言：我个人已经无力解决此问题。但又不是alist的锅，特此询问。
以**4d1ff3fdd643a64af872fd54dfcb06ca4b7c13c4**为例子（因为它只有40m好测试）
我是如何安装alist的：
```
docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist:latest
```
我是如何安装qbittorrent的：通过以下模板安装
```
 version: "2"
 services:
   qbittorrent:
     image: linuxserver/qbittorrent
     container_name: qbittorrent
     environment:
       - PUID=0
       - PGID=0
       - TZ=Asia/Shanghai # 你的时区
       - UMASK_SET=022    # （可选）默认022
       - WEBUI_PORT=8081  # WEB UI 端口 
     volumes:
       - /tmp/yourname/qbittorrent/config:/config
       - /tmp/yourname/qbittorrent/d:/downloads
     ports:
       - 6881:6881 # 最好更改，否者某些PT站点会屏蔽6881端口，为了避免被ISP屏蔽。⚠修改后，要在web界面同步修改
       - 6881:6881/udp
       - 8081:8081 # 考虑到CSRF和映射问题，内外端口必须与WEBUI_PORT一致。
     restart: unless-stopped
```
![image](https://github.com/alist-org/alist/assets/85008631/f43dd090-d13f-4821-8e73-6140c8019206)

它们出现了什么问题：
我可以由alist向qbittorrent下载请求可以下载
![image](https://github.com/alist-org/alist/assets/85008631/c940ce0b-3979-4910-894b-9b043bcb23c0)
但是无法从本地上传到微软盘。
![image](https://github.com/alist-org/alist/assets/85008631/11873d1a-8348-437a-a080-31667dfe9cc1)

下载的文件会被下载到qbittorrent的dock容器下的/opt/alist/data/temp/qBittorrent/位置
![image](https://github.com/alist-org/alist/assets/85008631/f3f7bc6d-cb1f-4674-8321-43bd98e1eb41)
我不知道该怎么解决此问题，请求帮助
