### DISCUSSION TITLE
请求支持在Docker部署Alist时通过环境变量设置二级域名(site_url)

### DISCUSSION THREAD

**Discussion by sogadm** [AlistGo/alist#6164] [Q&A] [answered]
在使用Docker部署Alist项目时，为便于快速部署和管理二级域名，是否可以考虑添加一个site_url环境变量以动态设置站点URL？如果有已存在的解决方案或未来计划，请告知。感谢！

期待您的回复。

**Comment by anwen-anyi** [comment]
? 不是已经有site url设置了吗

**Reply by sogadm** [reply]
```
  AList:
    container_name: "AList"
    restart: always
    volumes:
    - ./AList.db:/opt/alist/data/data.db
    - ./AList.json:/opt/alist/data/config.json

    environment:
    - PUID=0
    - PGID=0
    - UMASK=022
    - site url=/alist
    image: xhofe/alist:latest
```
`- site url=/alist`处设置环境变量没有用的,只能外挂`/opt/alist/data/config.json`文件修改`site_url`
