### DISCUSSION TITLE
docker下搭建alist搭配Postgres数据库报错

### DISCUSSION THREAD

**Discussion by DLL-ss** [AlistGo/alist#642] [Q&A]
docker搭建alis并使用Postgres数据库时报错：

can't get setting: ERROR: syntax error at or near "=" (SQLSTATE 42601)

配置文件是这样设置的，是不是我设置的不对呢，使用sqlite3数据库就能正常运行，麻烦解答下，谢谢！

{
  "address": "0.0.0.0",
  "port": 5244,
  "assets": "https://npm.elemecdn.com/alist-web@$version/dist",
  "database": {
    "type": "postgres",
    "user": "alist",
    "password": "xxxxx",
    "host": "xxxxx",
    "port": xxxxx,
    "name": "xxxxx",
    "table_prefix": "x_",
    "db_file": "data/data.db",
    "ssl_mode": "disable"
  },
  "scheme": {
    "https": false,
    "cert_file": "",
    "key_file": ""
  },
  "cache": {
    "expiration": 60,
    "cleanup_interval": 120
  },
  "temp_dir": "data/temp"

**Comment by xhofe** [comment]
postgres语法有些不适配，暂不支持。

**Reply by DLL-ss** [reply]
> postgres语法有些不适配，暂不支持。

哦哦，谢谢！

**Reply by YujiaCheng1996** [reply]
v3版能支持postgres了么？性能会比sqllite好一些。

**Reply by xhofe** [reply]
![image](https://user-images.githubusercontent.com/36558727/192558173-ede1460c-ffaa-424a-bda8-fb18e355aa70.png)
未发现有什么问题。

**Reply by YujiaCheng1996** [reply]
docker里跑起来了，是要多重试一会，一旦跑成功，重启啥的就没问题了。
docker-compose:
```
version: "3"

networks:
  alist:
    external: false

services:
  alist_db:
    container_name: alist_db
    image: postgres:13
    networks:
      - alist
    restart: always
    environment:
      - POSTGRES_USER=alist
      - POSTGRES_PASSWORD=alist
      - POSTGRES_DB=alist
    volumes:
      - /share/Docker/alist/postgres:/var/lib/postgresql/data

  alist:
    container_name: alist
    image: xhofe/alist:latest
    networks:
      - alist
    volumes:
      - /share/Docker/alist/data:/opt/alist/data
    ports:
      - 5245:5244
    depends_on:
      - alist_db
    restart: unless-stopped
```

config.json:
```
{
  "force": false,
  "address": "0.0.0.0",
  "port": 5244,
  "site_url": "",
  "cdn": "https://fastly.jsdelivr.net/npm/alist-web@$version/dist/",
  "jwt_secret": "AVEjR2oQhCdvcQcm",
  "token_expires_in": 48,
  "database": {
    "type": "postgres",
    "host": "alist_db",
    "port": 5432,
    "user": "alist",
    "password": "alist",
    "name": "alist",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "disable"
  },
  "scheme": {
    "https": false,
    "cert_file": "",
    "key_file": ""
  },
  "temp_dir": "data/temp",
  "log": {
    "enable": true,
    "name": "log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  }
}
```
最新版docker镜像3.0.3，初次启动停止后修改config后重启动。
修改后第一次启动一会就停止，之后就无限重启，失败日志也没有什么有用的信息：
```
INFO[2022-09-28 01:32:27] reading config file: data/config.json        
INFO[2022-09-28 01:32:27] load config from env with prefix:            
INFO[2022-09-28 01:32:27] init logrus... 
```
会重启多次，并log多次这3行，但多次之后会成功，成功之后再重启啥的就没有问题了。
