### DISCUSSION TITLE
关于 Meilisearch 的使用

### DISCUSSION THREAD

**Discussion by aUsernameWoW** [AlistGo/alist#6830] [Show and tell]
我发现文档中对于 Meilisearch 并不是特别详细，故在项目 Discussion 部分分享一下个人的部署经验，希望能帮到后面的朋友们🌹

个人认为， Meilisearch 相比于 MySQL 和 SQLite 有巨大优势，因为我使用这两者构建索引时从来没构建完成过（），而 Meilisearch 大约耗时 15 秒就完成了。

以下为安装和配置步骤，如有纰漏，还请各位指正。

1. 为 Meilisearch 生成主密钥

```bash
openssl rand -hex 16
```

2. 使用 Docker/Podman 运行 Meilisearch
请注意，Meilisearch 默认会监听 0.0.0.0:7700。若使用 host 网络，请注意检查防火墙设置，避免外部网络访问到 Meilisearch。

```yaml
version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=刚刚生成的密钥
    volumes:
      - ./meili_data:/meili_data #将 Meilisearch 的数据文件存储至 docker-compose.yml 相同目录下。
#    ports:
#      - "7700:7700"
    command: meilisearch --schedule-snapshot --snapshot-dir /meili_data/snapshots
    network_mode: "host" #使用host网路或者上方的端口映射都可以。此改动不会影响 Meilisearch 的默认端口号（7700）。
    restart: always
```

3. 在 AList 环境变量中配置 Meilisearch 

```json
{
  "force": ,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "",
  "token_expires_in": ,
  "database": {},
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "刚刚生成的密钥",
    "index_prefix": ""
  },
  "scheme": {},
  "temp_dir": "",
  "bleve_dir": "",
  "dist_dir": "",
  "log": {},
  "delayed_start": ,
  "max_connections": ,
  "tls_insecure_skip_verify": ,
  "tasks": {},
  "cors": {},
  "s3": {}
}
```

例如：

```yaml
version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=c5f15904a135ebfbbcbec4d0bfd30050
    volumes:
      - ./meili_data:/meili_data
#    ports:
#      - "7700:7700"
    command: meilisearch --schedule-snapshot --snapshot-dir /meili_data/snapshots
    network_mode: "host" #使用host网路或者上方的端口映射都可以。此改动不会影响 Meilisearch 的默认端口号（7700）。
    restart: always
```

```json
{
  "force": ,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "",
  "token_expires_in": ,
  "database": {},
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "c5f15904a135ebfbbcbec4d0bfd30050",
    "index_prefix": ""
  },
  "scheme": {},
  "temp_dir": "",
  "bleve_dir": "",
  "dist_dir": "",
  "log": {},
  "delayed_start": ,
  "max_connections": ,
  "tls_insecure_skip_verify": ,
  "tasks": {},
  "cors": {},
  "s3": {}
}
```

**Comment by ocean-zhc** [comment]
meilisearch 启用了https呢？好像不行了？

**Reply by aUsernameWoW** [reply]
我的 AList 和 Meilisearch 走的是本地回环连接，所以我也没实践过开启 HTTPS :(
但是理论上，只要给 Meilisearch 配置好了可信证书就能启动连接吧

**Comment by aUsernameWoW** [comment]
更新：截至今日，AList （目前最新版为v3.41.0）的 Meilisearch 依赖还停留在 v0.27.0，与之对应的最新 Meilisearch 版本为 v1.9.1，无法连接至更高版本。
在此更新一下docker-compose.yml

模板：
```
version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.9.1
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=刚刚生成的密钥
    volumes:
      - ./meili_data:/meili_data #将 Meilisearch 的数据文件存储至 docker-compose.yml 相同目录下。
#    ports:
#      - "7700:7700"
    command: meilisearch --schedule-snapshot --snapshot-dir /meili_data/snapshots
    network_mode: "host" #使用host网路或者上方的端口映射都可以。此改动不会影响 Meilisearch 的默认端口号（7700）。
    restart: always
```
开箱即用：
```
version: '3'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.9.1
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=c5f15904a135ebfbbcbec4d0bfd30050
    volumes:
      - ./meili_data:/meili_data
#    ports:
#      - "7700:7700"
    command: meilisearch --schedule-snapshot --snapshot-dir /meili_data/snapshots
    network_mode: "host" #使用host网路或者上方的端口映射都可以。此改动不会影响 Meilisearch 的默认端口号（7700）。
    restart: always
```

**Comment by WSL0809** [comment]
### 我也补充一个docker-compose 文件吧，把 alist 和 meilisearch 放在一块一键启动，亲测可用

```
version: '3.3'
services:
  alist:
    image: 'xhofe/alist:beta'
    container_name: alist
    volumes:
      - '/etc/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    networks:
      - my_network
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.9.1
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=c5f15904a135ebfbbcbec4d0bfd30050
    volumes:
      - ./meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
```

**Comment by ocean-zhc** [comment]
alist 3.45.0 
meilisearch 1.15.2 

重建索引，会提示网络错误以及alist 登陆token失效等

**Comment by nyaasuki** [comment]
```
services:
  alist:
    restart: always
    volumes:
      - './alist_data:/opt/alist/data'  
    ports:
      - '5244:5244'  
      - '5426:5426'  
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai 
      - MEILISEARCH_HOST=http://meilisearch:7700  
      - MEILISEARCH_API_KEY=your_master_key_here  # 替换为你的密钥
    container_name: alist
    image: 'xhofe/alist:latest'
    depends_on:
      - meilisearch 
    networks:
      - alist_network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=your_master_key_here  # 替换为你的密钥（与 AList 相同）
    volumes:
      - './meili_data:/meili_data'  
    ports:
      - '7700:7700'  
    networks:
      - alist_network
    restart: always
    command: meilisearch --schedule-snapshot --snapshot-dir /meili_data/snapshots

networks:
  alist_network:
    driver: bridge
```
上面的参数看起来有点迷糊 我也补充个自己用的compose配置
