### DISCUSSION TITLE
大佬们，能整一下吗？这个登录界面的logo，长方形的logo被压缩的厉害

### DISCUSSION THREAD

**Discussion by hcllmsx** [AlistGo/alist#6934] [Q&A] [answered]
2024年7月17日了，这个问题还没解决....0.0

强迫症患者表示很难受啊....

_Originally posted by @hcllmsx in https://github.com/alist-org/alist/issues/3517#issuecomment-2233149745_

**Comment by welcome** [comment]
Thanks for opening your first issue here! Be sure to follow the issue template!

**Comment by Simonzhang8** [comment]
一个临时解决办法是修改前端 https://github.com/alist-org/alist-web/blob/main/src/pages/login/index.tsx#L189 第189行，把boxSize去掉，改成w="100px" h="100px"的形式（数字根据自己图标的大小和实际需要自己填），然后自行编译前端后端运行

**Comment by hcllmsx** [comment]
> 一个临时解决办法是修改前端 https://github.com/alist-org/alist-web/blob/src/pages/login/index.tsx#L189 第189行，把boxSize去掉，改成w="100px" h="100px"的形式（数字根据自己图标的大小和实际需要自己填），然后自行编译前端后端运行

这个链接都打不开....404 - page not found . Cannot find a valid ref in src/pages/login/index.tsx

另外，算了，打开了修改了我也不会编译。还是等大佬修复。

**Comment by Simonzhang8** [comment]
> > 一个临时解决办法是修改前端 https://github.com/alist-org/alist-web/blob/main/src/pages/login/index.tsx#L189 第189行，把boxSize去掉，改成w="100px" h="100px"的形式（数字根据自己图标的大小和实际需要自己填），然后自行编译前端后端运行
> 
> 这个链接都打不开....404 - page not found . Cannot find a valid ref in src/pages/login/index.tsx
> 
> 另外，算了，打开了修改了我也不会编译。还是等大佬修复。

哦哦，我链接打错了，少打了个main；不过确实这个需要编译用，一键脚本手动安装的都不能用

**Comment by itsHenry35** [comment]
在自定义头部添加style，自己做一个css样式
https://alist.nn.ci/zh/config/global.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%B4%E9%83%A8

**Comment by YangZxi** [comment]
在自定义头部里填写以下内容
``` css
<style>
.hope-flex {flex-wrap: wrap;}
.hope-image {margin-right: none;flex: 1 1 100%;}
</style>
```

**Reply by itsHenry35** [reply, marked as answer]
理论上来说，应该这样，才不影响其他部件吧
``` css
<style>
.hope-c-PJLV-igBgqqg-css {flex-wrap: wrap;}
.hope-c-PJLV-ibwASZs-css {margin-right: none;flex: 1 1 100%;}
</style>
```

**Reply by YangZxi** [reply]
> 理论上来说，应该这样，才不影响其他部件吧
> 
> ```css
> <style>
> .hope-c-PJLV-igBgqqg-css {flex-wrap: wrap;}
> .hope-c-PJLV-ibwASZs-css {margin-right: none;flex: 1 1 100%;}
> </style>
> ```

是的，我没考虑到这里。你的方式是最好的，但是他在下一次编译后可能会变更名字（以 vue 的猜测）
所以也可以使用以下代码
``` css
<style>
#root > .hope-center > .hope-stack > .hope-flex:first-child {flex-wrap: wrap;}
#root > .hope-center > .hope-stack > .hope-flex:first-child > .hope-image {margin-right: unset;flex: 1 1 100%;}
</style>
```
