### DISCUSSION TITLE
Download speed through Alist is very slow

### DISCUSSION THREAD

**Discussion by kocey131** [AlistGo/alist#7782] [Q&A]
Hello, 

I am currently mounting storage from a storage box on hetzner using sftp. However the download speed does not exceed 1.8MB/s when download a file through Alsit which is very slow. (It is actually stuck at 1.8MB/s does not go up nor down)
I reach 50MB/s when using a sftp client such a FileZilla directly to the storage box.
Here is my docker-compose for reference: 

```
services:
    alist:
        image: 'xhofe/alist:latest'
        security_opt:
          - no-new-privileges:true
        container_name: alist
        networks:
          traefik_proxy:
            ipv4_address: 192.168.101.30
          socket_proxy:
        volumes:
            - $DOCKERDIR/appdata/alist/data:/opt/alist/data
            - $DOCKERDIR/logs/$HOSTNAME/alist/log.log:/opt/alist/data/log/log.log
        environment:
            - PUID=0
            - PGID=0
            - TZ=${TZ}
            - UMASK=022
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.alist-rtr.entrypoints=websecure"
          - "traefik.http.routers.alist-rtr.rule=Host(`filestation.$DOMAINNAME_1`)" 
          - "traefik.http.routers.alist-rtr.middlewares=chain-no-auth@file"
          - "traefik.http.routers.alist-rtr.service=alist-svc"
```
          
 Any ideas? 
 Thank you!
