### ISSUE TITLE
夸克网盘复制一个超过100个文件的目录时, 复制卡住不断占用内存直到宿主机死机

### ISSUE THREAD

**Issue by LQ2000** [AlistGo/alist#8333]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.44.0

### Driver used / 使用的存储驱动

夸克

### Describe the bug / 问题描述

我在 truenas 的容器和 ubuntu 的 docker 中安装的 alist 均出现了这个问题
在夸克网盘中存在一个文件夹, 里面超过了100个文件
选择将该目录复制到本机存储, 当复制到大概90个文件后, 所有文件的复制停止, 宿主机内存占用不断升高, 直到死机
相同文件夹在阿里网盘中复制到本机存储不会出现问题
尝试过不同文件夹, 不是某个特定文件夹独有的现象, 只要超过100个文件均会发生
旧版的软件没有这个问题

### Reproduction / 复现链接

https://github.com/qianguyihao/Web
试过把这个 repo 存入夸克中复制到本机会出现问题

### Config / 配置

```yaml
version: '3.3'
services:
  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
      - './data:/opt/alist/data'
      - './share:/opt/alist/share'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
```

![Image](https://github.com/user-attachments/assets/4da67902-01ad-4e0f-9597-63bc527408bf)

![Image](https://github.com/user-attachments/assets/84e179f4-cc5b-47da-9bd5-f5b5b35226de)

### Logs / 日志

![Image](https://github.com/user-attachments/assets/4fc7225f-4fe2-4215-95dc-48169c6c752c)
正在复制的文件显示等待重试后就卡住了
docker log 没有日志
